project:
  type: website
  output-dir: docs

website:
  title: "AHprojects"
  search: true
  page-navigation: true
  navbar: 
    background: "#011f4b" # https://www.color-hex.com/color-palette/1294
    foreground: "#6497b1" # https://www.color-hex.com/color-palette/1294
    left: 
      - text: "About"
        file: index.qmd
      - publications.qmd
      - tutorials.qmd
      - presentation.qmd
format:
  html:
    theme: cosmo
    toc: true