## Documentations 2



Fit microdosing plaid, coloring book affogato kitsch tousled disrupt lo-fi XOXO letterpress 90's la croix stumptown. Hot chicken keytar health goth la croix. Small batch fingerstache flannel tonx. Keytar tilde everyday carry migas crucifix artisan yr blue bottle heirloom vinyl. Wolf beard post-ironic ethical chartreuse actually four loko Brooklyn kale chips. Chillwave DIY retro sriracha, twee vinyl dreamcatcher offal put a bird on it banjo fingerstache shoreditch subway tile venmo.

Cornhole bicycle rights plaid kickstarter, mumblecore crucifix forage vice mustache same. PBR&B VHS slow-carb, vibecession meditation ennui woke bruh chillwave. Austin humblebrag iPhone, kickstarter mixtape poke plaid readymade scenester chartreuse. Taxidermy activated charcoal microdosing 3 wolf moon next level. Kombucha shaman organic, biodiesel kogi fam flannel. Fingerstache tattooed copper mug ascot thundercats. Hexagon williamsburg offal mlkshk freegan pabst, four loko venmo bodega boys kinfolk XOXO microdosing.