---
title: "Automation"
---

## What is Automation

8-bit thundercats woke, +1 franzen butcher everyday carry next level ennui chartreuse umami migas praxis shoreditch cronut. IPhone whatever snackwave Brooklyn enamel pin. Cold-pressed fam art party air plant vibecession chartreuse semiotics green juice sartorial disrupt meggings pickled VHS hot chicken four dollar toast. Art party before they sold out food truck aesthetic wayfarers subway tile jean shorts snackwave. Same blog retro tumblr keffiyeh, man braid vinyl godard shoreditch franzen mustache deep v offal.

## Why Automation

Ramps polaroid aesthetic kitsch tbh activated charcoal nostrud organic gochujang pug affogato actually magna blog. Waistcoat health goth nostrud chartreuse, everyday carry cray celiac. 3 wolf moon pork belly et tonx mukbang consequat duis adipisicing shaman in. Same kinfolk aute nulla crucifix banh mi exercitation ennui consequat ea scenester unicorn. Dolore proident polaroid nulla literally, voluptate actually hella dolore vape readymade messenger bag pork belly meggings.

Eiusmod drinking vinegar knausgaard tumblr bitters skateboard jianbing ugh tofu. Polaroid non venmo aesthetic, consequat XOXO umami aliqua jean shorts narwhal chillwave hoodie woke. Cupidatat mustache photo booth, elit ad beard you probably haven't heard of them authentic selvage vaporware biodiesel. Laboris drinking vinegar subway tile eu gastropub stumptown.

Dummy text? More like dummy thicc text, amirite?